# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XPS_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from pathlib import Path
from PyQt5 import uic, QtWidgets
import sys
from XPS_analyzer import XPS_GraphWindow
from nexus_handling import get_nexus_data,get_nexus_data2
from nexusformat.nexus import nxload
from DataHandling import data_handling
from dat import dat_handling,dat_handling_I06, dat_handling_IELTS, xy_handling
import numpy as np

class XPS_SpectrumWindow(QtWidgets.QDialog):
    def __init__(self):
        super(XPS_SpectrumWindow,self).__init__()
        self.spectrum_energies = None
        self.spectrum_id_init = None
        self.spectrum_id_final = None
        self.initUI() 

    def initUI(self):
        #loads the UI from the .ui file
        path = Path("UIWidgets")
        filename = path / "XPS_selectspectrums.ui"
        uic.loadUi(filename,self)
        self.energies_combo = self.findChild(QtWidgets.QComboBox,"comboBox_Select_Index")
        self.no_of_spectrums_combo = self.findChild(QtWidgets.QComboBox,"comboBox_No_Of_Spectrum")
        self.done_button = self.findChild(QtWidgets.QPushButton,"button_Done")
        self.energies_combo.currentIndexChanged.connect(self.load_data)
        self.no_of_spectrums_combo.currentIndexChanged.connect(self.load_data)
        self.done_button.clicked.connect(self.done1)
        #window is now displayed
        self.show()
        return

    def set_energy_item(self):
        self.energies_combo.clear()
        for i in range(len(self.spectrum_energies)):
            item = "ind" + str(i) + ":" + str(self.spectrum_energies[i])
            self.energies_combo.addItem(item)
        return
    
    def load_data(self):
        self.spectrum_id_init = self.energies_combo.currentIndex()
        self.spectrum_id_final = int(self.spectrum_id_init) + int(self.no_of_spectrums_combo.currentText())
        return
    
    def done1(self):
        self.close()
        return
    
class XPS_UI_Main(QtWidgets.QMainWindow):
    """Class containing all the information for the main window of program, the multiple display area (mdi)
    the functions called here load the data from source files and distribute it to windows where it needs to go"""
    
    #class constructor
    def __init__(self):
        #keeps track of the number of windows open
        self.window_count = 0
        #the file path of the file to be loaded
        self.file = None
        #the data from a vamas file, if applicable
        self.vms = None
        #the data from a dat file, if applicable
        self.dat = None
        #the data from a xy file, if applicable
        self.xy = None
        #the data from a nexus file, if applicable
        self.nxs_data = None
        #the metadata from a nexus file, if applicable
        self.nxs_meta = None
        #defines if data is loaded from a map
        self.is_mapp = False
        #the spectrum id of the first spectrum in the map
        self.spectrum_id_init = None
        #the spectrum id of the last spectrum in the map
        self.spectrum_id_final = None
        #makes the class a subclass of QMainWindow
        super(XPS_UI_Main,self).__init__()
        #loads the UI from the .ui file and assigns values to objects in that file
        self.initUI()
        
    def initUI(self):
        #loads the UI from the .ui file
        path = Path("UIWidgets")
        filename = path / "XPS_UI.ui"
        uic.loadUi(filename,self)

        #assigns values to objects, mdi area and graf button
        self.mdi = self.findChild(QtWidgets.QMdiArea, "mdiArea")
        self.graf_button = self.findChild(QtWidgets.QPushButton,"graf")
        self.grafsss = self.findChild(QtWidgets.QPushButton,"grafsss")
        #connects the button to the function that opens the graph window
        self.graf_button.clicked.connect(self.spectrum_single)
        self.grafsss.clicked.connect(self.from_map)
        #sets the menu bar in the UI MDI window
        self.set_menu_functions()
        
        #window is now displayed
        self.show()
        return

    def set_menu_functions(self):
        self.menu = self.menuBar()
        #adds file menu to toolbar
        self.file_menu = self.menu.addMenu("File")
        #adds exit to file menu
        self.exit = QtWidgets.QAction("Exit", self)
        self.file_menu.addAction(self.exit)
        self.exit.triggered.connect(self.done1)
        
        #Adds the options menu to the toolbar
        self.options_menu = self.menu.addMenu("Options")
        #adds the apply to all option to the options menu
        self.apply_all_action = QtWidgets.QAction("Apply to All...", self)
        self.options_menu.addAction(self.apply_all_action)
        self.apply_all_action.triggered.connect(self.apply_to_all_subwindows)
        #adds the apply to all option to the options menu
        self.fit_all = QtWidgets.QAction("Fit All Peaks.", self)
        self.options_menu.addAction(self.fit_all)
        self.fit_all.triggered.connect(self.fit_all_peaks)

        self.save_all = QtWidgets.QAction("Save All Peaks.", self)
        self.options_menu.addAction(self.save_all)
        self.save_all.triggered.connect(self.save_mass_spectra)
        return

    def done1(self):
         self.close()
         return
    
    def spectrum_single(self):
        self.is_mapp = False
        self.window_graph()
        return

    def from_map(self):
        self.is_mapp = True
        self.window_graph()
        return

    def window_graph(self):
        """Function that opens a graph window and loads the data from the file into it, nexus files can contain multiple 
        spectra so the function will open a new window for each spectrum in the file"""
        
        #loads the data from the file
        self.load_data()
        #if the file is a nexus file, it will open a new window for each spectrum in the file
        if self.file[-3:] == "nxs":
            for i, _ in enumerate(self.nxs_data):
                #adds one to window count
                self.window_count += 1
                #initilez the class containing the graph window object and its functions
                self.graph_window = XPS_GraphWindow()
                #sets the title of the window to the file name
                self.graph_window.setWindowTitle(self.file)
                #assigns the data of the ith nexus region to the graph window object
                self.graph_window.nxs = self.nxs_data[i]
                self.graph_window.meta = self.nxs_meta
            #initalizes the data for the region (initalize data function on the XPS_analyzer file)
                self.graph_window.initalize_data()
                #adds the graph window to the mdi area
                self.mdi.addSubWindow(self.graph_window)
                #shows the graph window
                self.graph_window.show()

        #if the file is a vamas file, it will open a new window for the file
        elif self.file[-3:] == "vms":
            self.window_count += 1
            #adds one to window count
            self.graph_window = XPS_GraphWindow()
            #sets the title of the window to the file name
            self.graph_window.setWindowTitle(self.file)
            #assigns data to graph window object
            self.graph_window.vms = self.vms
            #initalizes the data for the region (initalize data function on the XPS_analyzer file)
            self.graph_window.initalize_data()
            #adds the graph window to the mdi area
            self.mdi.addSubWindow(self.graph_window)
            #shows the graph window
            self.graph_window.show()
        #if the file is a dat file, it will open a new window for the file
        elif self.file[-3:] == "dat":
            for i, _ in enumerate(self.dat):
                self.window_count += 1
                #adds one to window count
                self.graph_window = XPS_GraphWindow()
                #sets the title of the window to the file name
                self.graph_window.setWindowTitle(self.file)
                #assigns data to graph window object
                self.graph_window.dat = self.dat[i]
                #initalizes the data for the region (initalize data function on the XPS_analyzer file)
                self.graph_window.initalize_data()
                #adds the graph window to the mdi area
                self.mdi.addSubWindow(self.graph_window)
                #shows the graph window
                self.graph_window.show()
        elif self.file[-3:] == self.file[-3:] == ".xy":
            self.window_count += 1
            #adds one to window count
            self.graph_window = XPS_GraphWindow()
            #sets the title of the window to the file name
            self.graph_window.setWindowTitle(self.file)
            #assigns data to graph window object
            self.graph_window.xy = self.xy
            #initalizes the data for the region (initalize data function on the XPS_analyzer file)
            self.graph_window.initalize_data()
            #adds the graph window to the mdi area
            self.mdi.addSubWindow(self.graph_window)
            #shows the graph window
            self.graph_window.show()
        #if neither is possible displays this error message
        else:
            print("could not open file")
        return

    def load_data(self):
       
        """Function that opens a file dialog and loads the file name as a string into the file variable,
       if the file is a nexus file or a vamas file"""
       
       #opens a file dialog and assigns the file name to the file variable
        self.file, _ = QtWidgets.QFileDialog.getOpenFileName(self,"Open VMS File","", "Vamas Files (*.vms);;Nexus Files (*.nxs);;All Files (*)")
        # if its a nexus file calls the functions nxload and get nexus data to create a variable containing the data
        if self.file[-3:] == "nxs" and self.is_mapp == False:
            nexus_file = nxload(self.file)
            self.nxs_data, self.nxs_meta = get_nexus_data(nexus_file)
        elif self.file[-3:] == "nxs" and self.is_mapp == True:
            file = nxload(self.file)
            self.nxs_data, self.nxs_meta = get_nexus_data2(file)
            excitation_energy = self.nxs_meta[0]["excitation_energy"]
            energies = self.nxs_meta[0]["energies"][0]
            spectrum_data = self.nxs_meta[0]["spectrum_data"]            
            #opens box to allow user to select spectrum range from map
            self.spectrum_window =  XPS_SpectrumWindow()
            self.spectrum_window.setWindowTitle("Select Spectrum")
            self.spectrum_window.spectrum_energies = excitation_energy
            self.spectrum_window.set_energy_item()
            self.spectrum_window.exec_()
            self.spectrum_id_init = self.spectrum_window.spectrum_id_init
            self.spectrum_id_final = self.spectrum_window.spectrum_id_final
            hvi = np.arange(self.spectrum_id_init,self.spectrum_id_final)
            self.nxs_data = []
            for i in range(len(hvi)):
                self.nxs_data.append({"x" : energies, "y" : spectrum_data[hvi[i]]}) 
        # if its a vamas file calls the function open vamas file to create a variable containing the data
        elif self.file[-3:] == "vms":
            self.vms = data_handling.open_vamas_file(self.file)
        #if neither is possible the function returns without any assignment
        elif self.file[-3:] == "dat":
            self.dat = dat_handling_IELTS(self.file)
        elif self.file[-3:] == ".xy":
            self.xy = xy_handling(self.file)
        else:
            pass
        return
    
    def apply_to_all_subwindows(self):
        """Function that applies the current settings to all subwindows"""
        #select active window
        active_window = self.mdi.activeSubWindow().widget()
        #if the active window is not none
        if active_window is not None:
            #if the active window is a graph window
            if active_window.objectName() == "PeakGraph":
                #apply settings to active window
                settings_names,settings = self.get_settings(active_window)
                print("settings names = ",settings_names)
                #for each window in the mdi area
                for window in self.mdi.subWindowList():
                    #if the window is a graph window
                    if window.widget().objectName() == "PeakGraph":
                        #if the window is not the active window
                        #apply settings to the window
                        self.set_settings(settings_names,settings,window.widget())
                        self.enable_GUI_functions(window.widget())
        return

    def get_settings(self,active_window):
        """Gets parameters from active window"""     
        settings_names = ["axis","sind","background_range","background_type","background","peak_no","inital_peak_positions","constraints","model_type","model_func","is_convoluded","model_prefix","fitting_method","model","pars","fit_results","fitted_array","peaks"]
        settings = []
        for name in settings_names:
            settings.append(getattr(active_window,name))
        return settings_names,settings
    
    def set_settings(self,settings_names,settings,window):
        """Sets constraints background and ranges to active window"""
        for name in settings_names:
            setting = settings[settings_names.index(name)]
            setattr(window,name,setting)
        return
    
    def enable_GUI_functions(self,window):
        """Enables GUI functions for window"""
        window.enable_fpeaks()
        if window.background is None:
            window.show_background_button.setDisabled(True)
        else:
            window.show_background_button.setEnabled(True)
        if window.inital_peak_positions is None:
            window.show_peakposotions_button.setDisabled(True)
        else:
            window.show_peakposotions_button.setDisabled(False)
        if window.fit_results is None:
            window.show_fittingcurve_button.setDisabled(True)
            window.show_fittedpeaks_button.setDisabled(True)
        else:
            window.show_fittingcurve_button.setEnabled(True)
            window.show_fittedpeaks_button.setEnabled(True)
        return
    
    
    def fit_all_peaks(self):
        """Iterates over all mdi subwindow and runs the fit peaks function on each window"""
        for window in self.mdi.subWindowList():
            if window.widget().objectName() == "PeakGraph":
                try:
                    
                    window.widget().initiate_fitting()
                except:
                    print("fitting failed for ", self.mdi.subWindowList().index(window))
                self.enable_GUI_functions(window.widget())
        return
    
    def total_area(self):
        """Iterates over all mdi subwindow and runs the total area function on each window"""
        area = np.zeros(len(self.mdi.subWindowList()))
        energy = np.zeros(len(self.mdi.subWindowList()))
        for window in self.mdi.subWindowList():
            i = 0
            if window.widget().objectName() == "PeakGraph":
                try:   
                    area[i] = np.trapz(window.widget().data[:,1] - window.widget().background)
                    energy[i] = window.widget().meta_data["excitation_energy"]
                except:
                    print("fitting failed for ", self.mdi.subWindowList().index(window))
            i+=1
        return area, energy
    
    def save_mass_spectra(self):
        """Iterates through spectra and runs the save spectra function on each window"""
        for window in self.mdi.subWindowList():
            if window.widget().objectName() == "PeakGraph":
                window.widget().save_spectra(enmass = True,file_prefix = "ArC60_bulkfilm_VoigtFit_  ",file_index = self.mdi.subWindowList().index(window))
        return


def main_window():
    """Function that initalizes the main window object and runs the program"""
    app = QtWidgets.QApplication(sys.argv)
    XPS_MainWindow = XPS_UI_Main()
    sys.exit(app.exec_())
    return


#runs main_window
main_window()


