# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XPS_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_XPS_MainWindow(object):
    def setupUi(self, XPS_MainWindow):
        XPS_MainWindow.setObjectName("XPS_MainWindow")
        XPS_MainWindow.resize(799, 602)
        XPS_MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(XPS_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graf = QtWidgets.QPushButton(self.centralwidget)
        self.graf.setGeometry(QtCore.QRect(210, 60, 91, 41))
        self.graf.setObjectName("graf")
        XPS_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(XPS_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        XPS_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(XPS_MainWindow)
        self.statusbar.setObjectName("statusbar")
        XPS_MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(XPS_MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(XPS_MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(XPS_MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(XPS_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(XPS_MainWindow)

    def retranslateUi(self, XPS_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        XPS_MainWindow.setWindowTitle(_translate("XPS_MainWindow", "MainWindow"))
        self.graf.setText(_translate("XPS_MainWindow", "Make Graf"))
        self.menuFile.setTitle(_translate("XPS_MainWindow", "File"))
        self.actionLoad.setText(_translate("XPS_MainWindow", "Load File"))
        self.actionSave.setText(_translate("XPS_MainWindow", "Save Data"))
        self.actionExit.setText(_translate("XPS_MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    XPS_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_XPS_MainWindow()
    ui.setupUi(XPS_MainWindow)
    XPS_MainWindow.show()
    sys.exit(app.exec_())
